name: Auto Deploy

on: [push]

jobs:
  build:
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: ${{ github.REPOSITORY }}
      REPO_URL: ${{ github.EVENT.REPOSITORY.CLONE_URL }}
      REPO_OWNER_NAME: ${{ github.EVENT.REPOSITORY.OWNER.NAME }}
      REPO_OWNER_EMAIL: ${{ github.EVENT.REPOSITORY.OWNER.EMAIL }}
      REPO_COMMIT_MESSAGE: ${{ github.EVENT.HEAD_COMMIT.MESSAGE }}
      REPO_BRANCH: "gh-pagess"
      REPO_LOCAL_DIR: ".deploy"
      GH_PAGES_EX=${{ $(git ls-remote --heads ${REPO_URL} ${REPO_BRANCH} | wc -l) }}
    runs-on: ubuntu-18.04
    steps:
    - name: Clone source repository
      uses: actions/checkout@v2
    - name: Configure destination branch
      run: |
        GH_PAGES_EXISTS=$(git ls-remote --heads ${REPO_URL} ${REPO_BRANCH} | wc -l)
        echo "GH_PAGES_EXISTS: $GH_PAGES_EXISTS"
        if [ "$GH_PAGES_EXISTS" == 1 ]; then
          echo "Cloning existent $REPO_BRANCH branch"
          git clone --single-branch --branch ${REPO_BRANCH} ${REPO_URL} ${REPO_LOCAL_DIR}
          cd ${REPO_LOCAL_DIR}
          git remote set-url origin https://${REPO_OWNER_NAME}:${REPO_TOKEN}@github.com/${REPO_NAME}.git
          git config user.email ${REPO_OWNER_EMAIL}
          git config user.name ${REPO_OWNER_NAME}
          git add .
          git commit -m "${REPO_COMMIT_MESSAGE}"
          git push
        else
          echo "Initializing and pushing to a new $REPO_BRANCH branch"
          mkdir ${REPO_LOCAL_DIR}
          cd ${REPO_LOCAL_DIR}
          git init
          git remote add origin https://${REPO_OWNER_NAME}:${REPO_TOKEN}@github.com/${REPO_NAME}.git
          git config user.email ${REPO_OWNER_EMAIL}
          git config user.name ${REPO_OWNER_NAME}
          git checkout -b ${REPO_BRANCH}
          echo test >> README.md
          git add .
          git commit -m "${REPO_COMMIT_MESSAGE}"
          git push -u origin ${REPO_BRANCH}
        fi
