name: Auto Deploy

on: [push]

jobs:
  build:
    env:
      gh-token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Project Node requirements installation
      run: npm install
    - name: Hexo CLI installation
      run: npm install -g hexo-cli
    - name: Static files genetation
      run: hexo generate
    - name: Set git identification
      run: |
        git config --global user.name "bluekrow"
        git config --global user.email "ndioses@gmail.com"     
    - name: Website deployment
      run: hexo deploy
      

