name: Hexo Auto Deploy

on: 
  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - README.md
    
jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:

    - name: Clone source repository
      uses: actions/checkout@v2      

    - name: Hexo Auto Deploy
      uses: bluekrow/hexo-auto-deploy@v1.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}