name: Hexo Auto Deploy

on: 
  push:
    branches:
    - master
    paths-ignore:
    - .gitignore
    - README.md
    
jobs:
  build:
    
    env:
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-18.04

    steps:
    - name: Clone source repository
      uses: actions/checkout@v2      

    - name: Hexo Auto Deploy
      uses: bluekrow/hexo-auto-deploy@v1.0.2
      with:
        token: ${AUTH_TOKEN}